### ISSUE TITLE
Update Travis config to not run release all the time

### ISSUE THREAD

**Issue by JamesSingleton** [americanexpress/one-app-cli#101]
Currently, the Travis config looks like:

```yaml
language: node_js
node_js:
  - 10
  - 12
  - 14
cache:
  directories:
  - node_modules
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches origin master && git fetch
before_deploy:
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
jobs:
  include:
    # Define the release stage that publishes lerna to npm
    - stage: release
      deploy:
          on:
            branch: master
          provider: script
          skip_cleanup: true
          script:
            - npm run lerna:deploy -- "${TRAVIS_COMMIT_MESSAGE}"
```

The issue with this is that the release job runs on every PR that is merged into master. Furthermore, it looks like it might not like multi-line commit messages. As both https://travis-ci.org/github/americanexpress/one-app-cli/jobs/703641806, as well as https://travis-ci.org/github/americanexpress/one-app-cli/jobs/699376611, failed at the _deploy_ job and causes a ❌with a failing build.

## Possible Solution

Run the deploy job when there is a specific commit message which is usually something along the lines of `chore(release): x.x.x`
